### ISSUE TITLE
Add a way of listing all stored objects

### ISSUE THREAD

**Issue by fmarczin** [amol-/depot#10] opened 2015-07-21 15:17 UTC
I miss a way of listing all objects stored in a depot, which would be really useful. Was this left out of the API intentionally, or could this be added?

**Comment by amol-** [comment] 2015-07-21 16:33
This is intentionally not provided to allow DEPOT to work with any storage system, even those that do not provide the concept of a file system or group of files. By DEPOT itself only a simple key-value access is supported and keeping track of files is demanded to another system (like DB if you are using SQLA or Ming support).

The feature can easily be implemented in a tool on top of depot, a depotfs or similar extension would make sense for use cases where a database keeping track of the files is not available. But it won't be part of depot itself by design.

**Comment by fmarczin** [comment] 2015-07-22 10:03
I certainly appreciate the idea of keeping an API compatible and sticking to the lowest common denominator. On the other hand, I can't think of a single storage system that does not provide a way of listing of keys (In DEPOT vocabulary: fileids, not filenames). Therefore I don't fully see the advantage in leaving it out.

**Comment by amol-** [comment] 2015-09-02 16:46
Still thinking about this, I'm planning to actually provide this as an extension and not inside the core layer.

That's because people might think that it's reliable while as you can actually configure multiple storages from the same source listing the files would actually list the files of all the storages, not the files of the specific storage.

For example... Suppose you have "avatars" and "thumbnails" both in "/tmp/files" if you ask for all files you would get all files in /tmp/files as there is no way to know which are from avatars and which are from thumbnails.

So I prefer to keep this api outside the core depot features and provide it as an extension, as tracking which files are uploaded is usually something bound to depot.fields and not to the low level Storage api.

**Comment by amol-** [comment] 2015-10-02 21:08
It's mostly handled in https://github.com/amol-/depot/pull/14

**Comment by amol-** [comment] 2015-10-03 13:45
This has been released in 0.2.0

**Closed by amol-** 2015-10-03 13:45 UTC
